name: SmartQuail Docker Build Apps QND41

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]
 
jobs:
  Docker_container_build:
    runs-on: ubuntu-latest
    env:
      DOMAIN: smartquail.io
      HOSTNAME: mail.smartquail.io
    steps:
    - name: Checkout code
      uses: actions/checkout@v3 
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Build container image
      working-directory: ./qnddovecot
      run: | 
        docker build -f Dockerfile \
            -t smartquail/qnddovecot:latest \
            -t smartquail/qnddovecot:${GITHUB_SHA::2}-${GITHUB_RUN_ID::2} \
            .
    - name: Push Image
      run: | 
        docker push smartquail/qnddovecot --all-tags
   

       

   
